name: nodejs-shop-demo
recipe: mean
config:
  node: 14
  globals:
    pm2: latest
  build:
    - npm install
  command: npm run test
  database: mysql
  port: '3000'
  ssl: false

services:
  database:
    portforward: 3307