name: CD

on: [ push ]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: [ ubuntu-latest ]
    steps:
      # - uses: actions/checkout@v1
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: cd ${{ secrets.SERVER_PATH }} && sh scripts/deploy.sh

